### ISSUE TITLE
Dynamic tags/labels not working

### ISSUE THREAD

**Issue by ogxd** [grafana/pyroscope-dotnet#52]
Hello!

Before anything, thanks a lot for this library, despite this issue, I find this tool to be a complete game changer for any performance-sensitive dotnet service 👏 

# Context

- I use the Pyroscope service **1.2.0** in K8S to profile dotnet 6 web applications (also in K8S). 
- I use the Pyroscope profiler **0.8.14**
- I use the Pyroscope nuget package  **0.8.14**
- I use the current environment variables for my dotnet service:
```
CORECLR_ENABLE_PROFILING=1
CORECLR_PROFILER={BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}
CORECLR_PROFILER_PATH=/app/Pyroscope.Profiler.Native.so
LD_PRELOAD=/app/Pyroscope.Linux.ApiWrapper.x64.so

PYROSCOPE_APPLICATION_NAME=ssbengine
PYROSCOPE_PROFILING_ENABLED=1
PYROSCOPE_PROFILING_CPU_ENABLED=1
PYROSCOPE_PROFILING_EXCEPTION_ENABLED=1
PYROSCOPE_PROFILING_ALLOCATION_ENABLED=1
PYROSCOPE_PROFILING_LOCK_ENABLED=1
PYROSCOPE_PROFILING_WALLTIME_ENABLED=0

PYROSCOPE_LABELS="version_env:123"
```

## Issue(s)

I am setting dynamic tags using the C# library like this:
```csharp
Profiler.Instance.ClearDynamicTags();
Profiler.Instance.SetDynamicTag("version_dynamic", "123");
```
I do not use the `LabelsWrapper` class.
### Expected
I expect the `version_dynamic` tag to show up in Pyroscope.
### Observed
I do not have `version_dynamic` tag showing up in Pyroscope.  
I have however the `version_env` tag that I have set from the environment variable `PYROSCOPE_LABELS`.  

## A few other remarks
- On the documentation/developer experience side, Pyroscope uses the "Tag" terminology, while `pyroscope-dotnet` names a tag a "Label" instead. This can be confusing.
- The readme explains how to use the `LabelWrapper` with a delegate action to wrap a code path with specific tags. While this can be an interesting feature, in my opinion, the principal usecase is setting tags once (`SetDynamicTag`(s)). I believe it is very worthy documenting this part.

**Comment by ogxd** [comment]
By looking at the C# Pyroscope package I am under the impression it just can't work as still has copy-pasted parts from the datadog package.
https://github.com/grafana/pyroscope-dotnet/blob/7b57217ab8c679a536ba098b2475780aeef4f9c6/Pyroscope/Pyroscope/NativeInterop.cs#L82
https://github.com/grafana/pyroscope-dotnet/blob/7b57217ab8c679a536ba098b2475780aeef4f9c6/Pyroscope/Pyroscope/ProfilerStatus.cs#L24

**Comment by Rperry2174** [comment]
We will do some digging and get back to you -- if you do use the `LabelWrapper` do dynamic tags work for you? 

https://github.com/grafana/pyroscope/blob/main/examples/dotnet/rideshare/example/OrderService.cs#L11-L13

**Comment by ogxd** [comment]
No, I haven't tried, but looking at what it does I don't think it is usable for sense in the context of a multithreaded web service since it statically sets/clears tags, hence doing this from different threads.  

From what I see it mostly does labels.Activate() which clears and adds tags
```csharp
public void Activate()
{
    Profiler.Instance.ClearDynamicTags();
    foreach ((string key, string str) in this._labels)
        Profiler.Instance.SetDynamicTag(key, str);
}
```
Which is what I tried on my end

**Comment by ogxd** [comment]
Ok I managed to make it work. I misunderstood how Dynamic Tags work (it's not documented). What I missed is that dynamic tags are cleared on every sample taken. In my case I want dynamic tags for all samples. So I had to create some routine to set the tags every X seconds. Kind of hacky, but it works.   

So there is no "bug" but still I think this C# library could benefit a lot from XML comments, renaming of labels to tags and a little more documentation in the readme (I can file a PR if you want, but maybe you are more aware of how things works here)

**Comment by raphaelquati** [comment]
I have the same situation: the PYROSCOPE_LABELS envvar is configured at helm values during a k8s deployment, but want to identify pod identification.

**Comment by raphaelquati** [comment]
> I have the same situation: the PYROSCOPE_LABELS envvar is configured at helm values during a k8s deployment, but want to identify pod identification.

I've fixed my case using a envvar ref in a other var (idea from https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/#define-an-environment-dependent-variable-for-a-container and https://stackoverflow.com/questions/73243744/combining-env-variables-in-helm-chart

Helm chart:

```
{{- $appname := include "default.name" . -}}
{{- $labels := print "namespace:" .Release.Namespace  ",app:" $appname ",pod:$(POD_NAME)" -}}
...

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PYROSCOPE_LABELS
              value: {{ $labels }}
```

This is not ideal, but works

**Comment by korniltsev** [comment]
I am closing as it seem to be resolved. Feel free to reopen if it does not work.

**Comment by ogxd** [comment]
Hello @korniltsev,
This issue was about dynamic tags. @raphaelquati 's issue is retated to labels set via environment variable, which are inherently non-dynamic.   
FYI since we opened this issue we (my company) are using a fork of this library which includes
- Working dynamic labels
- Ability to attach / detach, allowing other profilers to be used (otherwise the dotnet runtime prevents two profilers from being attached at a given time)
- Improvements over logging 

Let me know if you are interested, we'd gadly make this fork public. We currently lack a bit of time to submit proper PRs to this main repository.

**Comment by raphaelquati** [comment]
Hi @ogxd,

In my case, the trick I've used (setting the label at helm templates) - static labels - resolve our problem.
