### ISSUE TITLE
Musl - Arm64

### ISSUE THREAD

**Issue by hugobritoalves** [grafana/pyroscope-dotnet#67]
I would like to know if Pyroscope supports Alpine\Arm64. 

I saw the docker image that is supported, but the first test didn't work: [Img Docker](https://hub.docker.com/layers/pyroscope/pyroscope-dotnet/latest-musl/images/sha256-307cf7bbe94acf5c42d3f6cd6c38f745dd1aa4749d453dc89691216a759f2b56?context=explore)

**Comment by korniltsev** [comment]
It is not supported. The arm images are just stubs that will print a message "profiling not supported"
