### ISSUE TITLE
Bump dd-trace-dotnet to the last version

### ISSUE THREAD

**Issue by bodji** [grafana/pyroscope-dotnet#68]
Hi,

We are using pyroscope-dotnet to profile our C# applications with Pyroscope.

Unfortunately, the applications with profiling enabled are crashing every 1/2 days.

The crash seems very similar to these, related here: 
https://github.com/grafana/pyroscope-dotnet/issues/62

And it seems fixed with a newer version of dd-trace-dotnet: 
https://github.com/DataDog/dd-trace-dotnet/pull/4753

Would it be possible to bump to the last version of dd-trace-dotnet ?

Thanks a lot.

**Comment by raphaelquati** [comment]
I' have the same situation.

Containers keep crashing in a random manner.

I've collected the core dump (Windbg  print):



![Image](https://github.com/user-attachments/assets/d4309c10-3038-476a-b070-2fd907be8ac3)

**Comment by korniltsev** [comment]
> I've collected the core dump (Windbg print): 

What was the version used? @raphaelquati

**Comment by raphaelquati** [comment]
Hi,

My docker file:

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["NuGet.config", "."]
COPY ["src/xxx.Api/xxx.Api.csproj", "src/xxx.Api/"]
COPY ["src/xxx.Application.Abstractions/xxx.Application.Abstractions.csproj", "src/xxx.Application.Abstractions/"]
COPY ["src/xxx.Application/xxx.Application.csproj", "src/xxx.Application/"]
COPY ["src/xxx.Domain/xxx.Domain.csproj", "src/xxx.Domain/"]
COPY ["src/xxx.Infra.Data/xxx.Infra.Data.csproj", "src/xxx.Infra.Data/"]
COPY ["src/xxx.IntegrationEvents/xxx.IntegrationEvents.csproj", "src/xxx.IntegrationEvents/"]
RUN dotnet restore "src/xxx.Api/xxx.Api.csproj"
COPY . .
WORKDIR "/src/src/xxx.Api"
RUN dotnet build "xxx.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "xxx.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=pyroscope/pyroscope-dotnet:0.8.14-glibc /Pyroscope.Profiler.Native.so ./Pyroscope.Profiler.Native.so
COPY --from=pyroscope/pyroscope-dotnet:0.8.14-glibc /Pyroscope.Linux.ApiWrapper.x64.so ./Pyroscope.Linux.ApiWrapper.x64.so
ENTRYPOINT ["dotnet", "xxx.Api.dll"]
```

**Comment by korniltsev** [comment]
> My docker file:

Thanks for report, I will try to look at the failed instruction and functions
