### ISSUE TITLE
Profiling is disabled: It appears the wrapper library 'Datadog.Linux.ApiWrapper.x64.so' is not correctly load

### ISSUE THREAD

**Issue by AndrewP-GH** [grafana/pyroscope-dotnet#85]
After update I faced with the error
```
[2024-11-05 12:43:15.377 | info | PId: 1 | TId: 1] .NET Profiler deployment mode: Single Step Instrumentation
[2024-11-05 12:43:15.377 | info | PId: 1 | TId: 1] .NET Profiler is explictly enabled.
[2024-11-05 12:43:15.377 | info | PId: 1 | TId: 1] DllGetClassObject(): Returning an instance of CorProfilerCallbackFactory (hr=0x0)
[2024-11-05 12:43:15.378 | info | PId: 1 | TId: 1] CorProfilerCallback is initializing.
[2024-11-05 12:43:15.378 | info | PId: 1 | TId: 1] No "DD_TRACE_DEBUG" environment variable has been found. Enable debug log = 0 (default).
[2024-11-05 12:43:15.378 | info | PId: 1 | TId: 1] Environment variables:
[2024-11-05 12:43:15.378 | warning | PId: 1 | TId: 1] Profiling is disabled: It appears the wrapper library 'Datadog.Linux.ApiWrapper.x64.so' is not correctly loaded.
Possible reason(s):
* The LD_PRELOAD environment variable might not contain the path '/profiler/Datadog.Linux.ApiWrapper.x64.so'. Try adding '/profiler/Datadog.Linux.ApiWrapper.x64.so' to LD_PRELOAD environment variable.
* Your application might be running in a secure execution mode (false). Try adding the path '/profiler/Datadog.Linux.ApiWrapper.x64.so' to the /etc/ld.so.preload file (create the file if needed).
If the issue persists, please contact the support with the following details:
LD_PRELOAD current value: /profiler/Pyroscope.Linux.ApiWrapper.x64.so
The process running in a secure execution mode: false
Process User ID differs from Effective User ID: false
Process Group ID differs from Effective Group ID: false
```

**Comment by AndrewP-GH** [comment]
Envs:

PYROSCOPE_SERVER_ADDRESS:                                                http://pyroscope.infra-monitoring.svc.cluster.local:4040                             │
PYROSCOPE_PROFILING_ENABLED:                                             1                                                                                    │
CORECLR_ENABLE_PROFILING:                                                1                                                                                    │
PYROSCOPE_PROFILING_EXCEPTION_ENABLED:                                   1                                                                                    │
PYROSCOPE_PROFILING_ALLOCATION_ENABLED:                                  1                                                                                    │
PYROSCOPE_PROFILING_LOCK_ENABLED:                                        1                                                                                    │
PYROSCOPE_PROFILING_CPU_ENABLED:                                         1                                                                                    │
PYROSCOPE_PROFILING_WALLTIME_ENABLED:                                    1                                                                                    │
PYROSCOPE_PROFILING_LOG_DIR:                                             /tmp/log/pyroscope/                                                                  │
PYROSCOPE_LABELS:                                                        pod_name:$(POD_NAME),node_name:$(NODE_NAME),pod_ip:$(POD_IP)                         │
CORECLR_PROFILER:                                                        {BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}                                               │
CORECLR_PROFILER_PATH:                                                   /profiler/Pyroscope.Profiler.Native.so                                               │
LD_PRELOAD:                                                              /profiler/Pyroscope.Linux.ApiWrapper.x64.so

**Comment by dansowter** [comment]
Having the same issue. I'm not familiar enough with the project to find the issue, but I did manage to work around it by copying `Pyroscope.Linux.ApiWrapper.x64.so` to `Datadog.Linux.ApiWrapper.x64.so` and referencing both (space-delimited) in LD_PRELOAD.

Hope that helps someone else until this can be resolved.

**Comment by gmkado** [comment]
Had the same issue, changing Pyroscope to Datadog fixed it for me too

**Comment by korniltsev** [comment]
This was fixed in https://github.com/grafana/pyroscope-dotnet/pull/91
Now both `Pyroscope.Linux.ApiWrapper.x64.so` and `Datadog.Linux.ApiWrapper.x64.so`

There are no differences between  `Pyroscope.Linux.ApiWrapper.x64.so` and `Datadog.Linux.ApiWrapper.x64.so`. It was just renamed for obscure reasons and now we have to support both names and I broke the pyroscope name when updated datadog's for int 0.9.0.
