### ISSUE TITLE
Q: Disable console as logging output

### ISSUE THREAD

**Issue by klesta490** [grafana/pyroscope-dotnet#86]
Hello,
I am using pyroscope in k8s with my .NET apps and pyroscope logs are kind of flooding applications logs. Is there a way to disable logging to Console? 

Thanks Vladimir

**Comment by dlinkov-roblox** [comment]
Setting PYROSCOPE_LOG_STDERR=false as an environment variable will disable logging to std::err.

**Comment by klesta490** [comment]
Thanks @dlinkov-roblox !
